maintainer       "George London"
maintainer_email "4.business.email@gmail.com"
license          "MIT"
description      "Installs/Configures django_application_server"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"
depends "git"
depends "apt"
depends "nginx"
depends "python"
depends "nginx"
depends "rabbitmq"
depends "build-essential"
depends "postgresql"
depends "application"
depends "application_python"
depends "application_nginx"
depends "database"
